/**
 * Knetik Platform API Documentation Latest
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/// <reference path="api.d.ts" />

/* tslint:disable:no-unused-variable member-ordering */

namespace API.Client {
    'use strict';

    export class BRERuleEngineTriggersApi {
        protected basePath = 'https://localhost:8080/';
        public defaultHeaders : any = {};

        static $inject: string[] = ['$http', '$httpParamSerializer', 'basePath'];

        constructor(protected $http: ng.IHttpService, protected $httpParamSerializer?: (d: any) => any, basePath?: string) {
            if (basePath !== undefined) {
                this.basePath = basePath;
            }
        }

        private extendObj<T1,T2>(objA: T1, objB: T2) {
            for(let key in objB){
                if(objB.hasOwnProperty(key)){
                    objA[key] = objB[key];
                }
            }
            return <T1&T2>objA;
        }

        /**
         * Create a trigger
         * Customer added triggers will not be fired automatically or have rules associated with them by default. Custom rules must be added to get use from the trigger and it must then be fired from the outside. See the Bre Event services
         * @param breTriggerResource The BRE trigger resource object
         */
        public createTriggerUsingPOST (breTriggerResource?: BreTriggerResource, extraHttpRequestParams?: any ) : ng.IHttpPromise<BreTriggerResource> {
            const localVarPath = this.basePath + '/bre/triggers';

            let queryParameters: any = {};
            let headerParams: any = this.extendObj({}, this.defaultHeaders);
            let httpRequestParams: any = {
                method: 'POST',
                url: localVarPath,
                json: true,
                data: breTriggerResource,
                                params: queryParameters,
                headers: headerParams
            };

            if (extraHttpRequestParams) {
                httpRequestParams = this.extendObj(httpRequestParams, extraHttpRequestParams);
            }

            return this.$http(httpRequestParams);
        }
        /**
         * Delete a trigger
         * May fail if there are existing rules against it. Cannot delete core triggers
         * @param eventName The trigger event name
         */
        public deleteTriggerUsingDELETE (eventName: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
            const localVarPath = this.basePath + '/bre/triggers/{event_name}'
                .replace('{' + 'event_name' + '}', String(eventName));

            let queryParameters: any = {};
            let headerParams: any = this.extendObj({}, this.defaultHeaders);
            // verify required parameter 'eventName' is not null or undefined
            if (eventName === null || eventName === undefined) {
                throw new Error('Required parameter eventName was null or undefined when calling deleteTriggerUsingDELETE.');
            }
            let httpRequestParams: any = {
                method: 'DELETE',
                url: localVarPath,
                json: true,
                                                params: queryParameters,
                headers: headerParams
            };

            if (extraHttpRequestParams) {
                httpRequestParams = this.extendObj(httpRequestParams, extraHttpRequestParams);
            }

            return this.$http(httpRequestParams);
        }
        /**
         * Get a single trigger
         * 
         * @param eventName The trigger event name
         */
        public getTriggerUsingGET (eventName: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<BreTriggerResource> {
            const localVarPath = this.basePath + '/bre/triggers/{event_name}'
                .replace('{' + 'event_name' + '}', String(eventName));

            let queryParameters: any = {};
            let headerParams: any = this.extendObj({}, this.defaultHeaders);
            // verify required parameter 'eventName' is not null or undefined
            if (eventName === null || eventName === undefined) {
                throw new Error('Required parameter eventName was null or undefined when calling getTriggerUsingGET.');
            }
            let httpRequestParams: any = {
                method: 'GET',
                url: localVarPath,
                json: true,
                                                params: queryParameters,
                headers: headerParams
            };

            if (extraHttpRequestParams) {
                httpRequestParams = this.extendObj(httpRequestParams, extraHttpRequestParams);
            }

            return this.$http(httpRequestParams);
        }
        /**
         * List triggers
         * 
         * @param filterSystem Filter for triggers that are system triggers when true, or not when false. Leave off for both mixed
         * @param filterCategory Filter for triggers that are within a specific category
         * @param filterName Filter for triggers that have names containing the given string
         * @param size The number of objects returned per page
         * @param page The number of the page returned, starting with 1
         */
        public getTriggersUsingGET (filterSystem?: boolean, filterCategory?: string, filterName?: string, size?: number, page?: number, extraHttpRequestParams?: any ) : ng.IHttpPromise<PageResourceBreTriggerResource> {
            const localVarPath = this.basePath + '/bre/triggers';

            let queryParameters: any = {};
            let headerParams: any = this.extendObj({}, this.defaultHeaders);
            if (filterSystem !== undefined) {
                queryParameters['filter_system'] = filterSystem;
            }

            if (filterCategory !== undefined) {
                queryParameters['filter_category'] = filterCategory;
            }

            if (filterName !== undefined) {
                queryParameters['filter_name'] = filterName;
            }

            if (size !== undefined) {
                queryParameters['size'] = size;
            }

            if (page !== undefined) {
                queryParameters['page'] = page;
            }

            let httpRequestParams: any = {
                method: 'GET',
                url: localVarPath,
                json: true,
                                                params: queryParameters,
                headers: headerParams
            };

            if (extraHttpRequestParams) {
                httpRequestParams = this.extendObj(httpRequestParams, extraHttpRequestParams);
            }

            return this.$http(httpRequestParams);
        }
        /**
         * Update a trigger
         * May fail if new parameters mismatch requirements of existing rules. Cannot update core triggers
         * @param eventName The trigger event name
         * @param breTriggerResource The BRE trigger resource object
         */
        public updateTriggerUsingPUT (eventName: string, breTriggerResource?: BreTriggerResource, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
            const localVarPath = this.basePath + '/bre/triggers/{event_name}'
                .replace('{' + 'event_name' + '}', String(eventName));

            let queryParameters: any = {};
            let headerParams: any = this.extendObj({}, this.defaultHeaders);
            // verify required parameter 'eventName' is not null or undefined
            if (eventName === null || eventName === undefined) {
                throw new Error('Required parameter eventName was null or undefined when calling updateTriggerUsingPUT.');
            }
            let httpRequestParams: any = {
                method: 'PUT',
                url: localVarPath,
                json: true,
                data: breTriggerResource,
                                params: queryParameters,
                headers: headerParams
            };

            if (extraHttpRequestParams) {
                httpRequestParams = this.extendObj(httpRequestParams, extraHttpRequestParams);
            }

            return this.$http(httpRequestParams);
        }
    }
}
