/**
 * Knetik Platform API Documentation Latest
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/// <reference path="api.d.ts" />

namespace API.Client {
    'use strict';

    export interface QuestionTemplateResource {
        /**
         * A property definition for all answers. If included each answer must match this definition's type and be valid
         */
        "answerProperty"?: PropertyDefinitionResource;

        /**
         * The date/time this resource was created in seconds since unix epoch
         */
        "createdDate"?: number;

        /**
         * The id of the template
         */
        "id"?: string;

        /**
         * The name of the template
         */
        "name": string;

        /**
         * The customized properties that are present
         */
        "properties"?: Array<PropertyDefinitionResource>;

        /**
         * A property definition for the question itself. If included the answer must match this definition's type and be valid
         */
        "questionProperty"?: PropertyDefinitionResource;

        /**
         * The date/time this resource was last updated in seconds since unix epoch
         */
        "updatedDate"?: number;

    }

}
