/**
 * Knetik Platform API Documentation Latest
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/// <reference path="api.d.ts" />

namespace API.Client {
    'use strict';

    export interface Video {
        "active"?: boolean;

        "author"?: Artist;

        "authored"?: number;

        "banned"?: boolean;

        "categoryId"?: string;

        "categoryName"?: string;

        "contributors"?: CollectionVideoContribution;

        "created"?: number;

        "embed"?: string;

        "extension"?: string;

        "height"?: number;

        "id"?: number;

        "length"?: number;

        "location"?: string;

        "longDescription"?: string;

        "mimeType"?: string;

        "name"?: string;

        "priority"?: number;

        "privacy"?: Video.PrivacyEnum;

        "published"?: boolean;

        "shortDescription"?: string;

        "size"?: number;

        "tags"?: Array<VideoTag>;

        "thumbnail"?: string;

        "updated"?: number;

        "uploader"?: User;

        "views"?: number;

        "whitelist"?: Array<User>;

        "width"?: number;

    }

    export namespace Video {
        export enum PrivacyEnum {
            Private = <any> 'private',
            Friends = <any> 'friends',
            Public = <any> 'public'
        }
    }
}
